FxProperties/FxProperties/Controllers/PropertyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Cryptography;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using DotNetOpenAuth.Messaging;
using FxProperties.Models;

namespace FxProperties.Code
{
    //[Authorize]
    public class PropertyController : Controller
    {
        //
        // GET: /Property/

        public ActionResult Index()
        {
            var propNames = new List<string>() {
                "Fx of Point West",
                "Pelican's Landing Condominiums",
                "Miami Gardens",
                "Fx of Birch Brook Apartments",
                "Fx of West Park Apartments",
                "Fx of Dairy Ashford Apartments",
                "Fx of Kirkwood Apartments",
                "Fx of Town Park Apartments",
                "Fx of Deer Park Apartments",
                "Fx of Beechnut Apartments",
                "Fx of Edgebrook Apartments",
                "Fx of West Oaks",
                "Villagekey Apartments"
            };

            var props = new List<PropertyModel>();

            foreach (var propName in propNames)
            {
                var prop = new PropertyModel();
                prop.Name = propName;
                prop.Address = "245 E 20th St, New York, NY 201609";
                prop.Buildings = 10;
                prop.Units = 50;
                prop.Supervisor = 1;
                prop.LeaseAgent = 1;
                prop.Occupied = 40;
                prop.Vacant = 10;
                prop.VacancyPercentage = 20;

                props.Add(prop);
            }


            var db = new UsersContext();
            var fname = db.UserProfiles.First(x => x.UserName == User.Identity.Name);
            return View(props);
        }

        public ActionResult List()
        {
            var propNames = new List<string>() {
                "Fx of Point West",
                "Pelican's Landing Condominiums",
                "Miami Gardens",
                "Fx of Birch Brook Apartments",
                "Fx of West Park Apartments",
                "Fx of Dairy Ashford Apartments",
                "Fx of Kirkwood Apartments",
                "Fx of Town Park Apartments",
                "Fx of Deer Park Apartments",
                "Fx of Beechnut Apartments",
                "Fx of Edgebrook Apartments",
                "Fx of West Oaks",
                "Villagekey Apartments"
            };

            var props = new List<PropertyModel>();

            foreach (var propName in propNames)
            {
                var prop = new PropertyModel();
                prop.Name = propName;
                prop.Address = "245 E 20th St, New York, NY 201609";
                prop.Buildings = 10;
                prop.Units = 50;
                prop.Supervisor = 1;
                prop.LeaseAgent = 1;
                prop.Occupied = 40;
                prop.Vacant = 10;
                prop.VacancyPercentage = 20;

                props.Add(prop);
            }


            var db = new UsersContext();
            //var fname = db.UserProfiles.First(x => x.UserName == User.Identity.Name);
            return View(props);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PropertyModel model)
        {
            if (ModelState.IsValid)
            {
                using (var ctx = new FxPropertiesEntities())
                {
                    ctx.Properties.Add(new Property()
                    {
                        Name = model.Name,
                        Address = model.Address,
                        City = model.City,
                        LeasingAgent = model.LeaseAgent,
                        Supervisor = model.Supervisor,
                        State = model.State
                    });

                    ctx.SaveChanges();
                }
            }

            return View(model);
        }

        public ActionResult Create()
        {
            var prop = new PropertyModel();
            return View(prop);
        }

        public ActionResult Config()
        {
            return View();
        }

        public ActionResult Test()
        {
            var unitList = new List<UnitModel>();
            using (var ctx = new FxPropertiesEntities())
            {
                var units = ctx.Units.Where(u => u.Building.PropertyId == 1 && u.Status == 1).ToList();

                unitList.AddRange(units.Select(unit => new UnitModel()
                {
                    Id = unit.Id, 
                    Type = unit.Type ?? default(int), 
                    Area = unit.Area ?? default(float), 
                    Rent = unit.Rent ?? default(decimal)
                }));
            }

            return View(unitList);
        }
    }
}

FxProperties/FxProperties/Views/Shared/_FxLayout.cshtml
@using FxProperties.Code
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - Fx Property Management</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
    <!-- Favicon-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Select Css -->
    <link href="~/resources/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet">
    <!-- Custom Css -->
    <link href="~/resources/css/main.css" rel="stylesheet">
    <link href="~/resources/css/themes/all-themes.css" rel="stylesheet">

    @*<link href="https://fonts.googleapis.com/css?family=Anton|Merriweather" rel="stylesheet">*@

    @*@Styles.Render("~/Content/css")*@
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="theme-blue">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-blue">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->

    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->

    <!-- Top Bar -->
    <nav class="navbar clearHeader">
        <div class="container-fluid">
            <div class="navbar-header">
                <a href="javascript:void(0);" class="bars"></a><a class="navbar-brand" href="index.html">
                    @*<img src="~/resources/images/logo.png" class="logo" alt="Fx::Rentroll">*@</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                
                @{
                    <!-- Notifications -->
                    Html.RenderPartial("_FxNotification");
                    
                    <!-- Tasks -->
                    Html.RenderPartial("_FxTasks");
                }
            </ul>
        </div>
    </nav>
    <!-- #Top Bar -->

    <!--Side menu and right menu -->
    <section>
        <!-- Left Sidebar -->
        @{
            Html.RenderPartial("_FxLeftSidebar");
        }
    </section>

    <!-- main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>@ViewBag.Header</h2>
                <small class="text-muted">Welcome to Fx Property Management App</small>
            </div>
            @RenderBody()
        </div>
    </section>
    <!-- main content -->

    <div class="color-bg"></div>

    <!-- Jquery Core Js -->
    <script src="~/resources/bundles/libscripts.bundle.js"></script>
    <!-- Lib Scripts Plugin Js -->
    <script src="~/resources/bundles/vendorscripts.bundle.js"></script>
    <!-- Lib Scripts Plugin Js -->
    <script src="~/resources/bundles/mainscripts.bundle.js"></script>
</body>

@RenderSection("scripts", required: false)
</html>

FxProperties/FxProperties/Views/Shared/_FxLeftSidebar.cshtml
@using FxProperties.Code
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        <div class="admin-image">
            <img src="~/resources/images/User.png" alt="">
        </div>
        <div class="admin-action-info">
            <span>Welcome</span>
            @*<h3>@User.Identity.GetUserName()</h3>*@
            <ul>
                <li><a data-placement="bottom" title="Go to Profile" href="profile.html"><i class="zmdi zmdi-account"></i></a></li>
                @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm" }))
                {
                    @Html.AntiForgeryToken()
                    <li><a data-placement="bottom" title="Log out" href="javascript:document.getElementById('logoutForm').submit()"><i class="zmdi zmdi-sign-in"></i></a></li>
                }
            </ul>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>
            <li class="open"><a href="index.html"><i class="zmdi zmdi-home"></i><span>Home</span></a></li>
            <li class="open"><a href="dashboard.html"><i class="zmdi zmdi-file-text"></i><span>Dashboard</span></a></li>
            <li><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-city"></i><span>Properties</span> </a>
                <ul class="ml-menu">
                    <li>@Html.ActionLink("Create Property", "Create", "Property")</li>
                </ul>
            </li>
            <li class="open"><a href="javascript:void(0);" class="menu-toggle"><i class="zmdi zmdi-accounts-outline"></i><span>Users</span> </a>
                <ul class="ml-menu">
                    <li>@Html.ActionLink("Add User", "Register", "Account")</li>
                    @*<li><a href="user-create-supervisor.html">Create Supervisor</a></li>*@
                </ul>
            </li>
        </ul>
    </div>
    <!-- #Menu -->
</aside>

FxProperties/FxProperties/Views/Shared/_FxLoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>Fx::Rentroll - Sign in</title>
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Favicon-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Custom Css -->
    <link href="~/resources/css/main.css" rel="stylesheet">
    <link href="~/resources/css/login.css" rel="stylesheet">
</head>
<body class="login-page authentication">
<div class="container">
    <div class="card-top"></div>
    <div class="card">
        <h1 class="title"><span>Fx::Rentroll</span>Login <span class="msg">Sign in to start your session</span></h1>
        <div class="col-md-12">
            @RenderBody()
            
        </div>
    </div>
</div>
<div class="theme-bg"></div>

<!-- Jquery Core Js -->
<script src="~/resources/bundles/libscripts.bundle.js"></script> <!-- Lib Scripts Plugin Js -->
<script src="~/resources/bundles/vendorscripts.bundle.js"></script> <!-- Lib Scripts Plugin Js -->

<script src="~/resources/bundles/mainscripts.bundle.js"></script>
<!-- Custom Js -->
<script src="~/resources/js/pages/sign-in.js"></script>
</body>
</html>

FxProperties/FxProperties/Views/Shared/_FxNotification.cshtml
<li class="dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"><i class="zmdi zmdi-notifications"></i><span class="label-count">7</span> </a>
    <ul class="dropdown-menu">
        <li class="header">NOTIFICATIONS</li>
        <li class="body">
            <ul class="menu">
                <li><a href="javascript:void(0);">
                    <div class="icon-circle bg-light-green"><i class="zmdi zmdi-account-add"></i></div>
                    <div class="menu-info">
                        <h4>Deposit received for Unit 110 Fx of Bellair</h4>
                        <p><i class="material-icons">access_time</i> 14 mins ago </p>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <div class="icon-circle bg-cyan"><i class="zmdi zmdi-shopping-cart-plus"></i></div>
                    <div class="menu-info">
                        <h4>Notice sent to Unit 103 Fx of Bellair</h4>
                        <p><i class="material-icons">access_time</i> 22 mins ago </p>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <div class="icon-circle bg-red"><i class="zmdi zmdi-delete"></i></div>
                    <div class="menu-info">
                        <h4>Lease create for Unit 120 Fx of Bellair</h4>
                        <p><i class="material-icons">access_time</i> 3 hours ago </p>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <div class="icon-circle bg-orange"><i class="zmdi zmdi-edit"></i></div>
                    <div class="menu-info">
                        <h4>Deposit received for Unit 340 Fx of Town Park</h4>
                        <p><i class="material-icons">access_time</i> 2 hours ago </p>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <div class="icon-circle bg-blue-grey"><i class="zmdi zmdi-comment-alt-text"></i></div>
                    <div class="menu-info">
                        <h4>Expiring today Lease for Unit 510 Pelican Landing</h4>
                        <p><i class="material-icons">access_time</i> 4 hours ago </p>
                    </div>
                </a></li>
            </ul>
        </li>
        <li class="footer"><a href="javascript:void(0);">View All Notifications</a> </li>
    </ul>
</li>

FxProperties/FxProperties/Views/Shared/_FxTasks.cshtml
<li class="dropdown"><a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button"><i class="zmdi zmdi-flag"></i><span class="label-count">9</span> </a>
    <ul class="dropdown-menu">
        <li class="header">TASKS</li>
        <li class="body">
            <ul class="menu tasks">
                <li><a href="javascript:void(0);">
                    <h4>Plumbing for Unit 110 Fx of Bellair <small>32%</small> </h4>
                    <div class="progress">
                        <div class="progress-bar bg-pink" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 32%"></div>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <h4>Painting for Unit 103 Fx of Bellair <small>45%</small> </h4>
                    <div class="progress">
                        <div class="progress-bar bg-cyan" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 45%"></div>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <h4>Plumbing for Unit 120 Fx of Bellair <small>54%</small> </h4>
                    <div class="progress">
                        <div class="progress-bar bg-teal" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 54%"></div>
                    </div>
                </a></li>
                <li><a href="javascript:void(0);">
                    <h4>Plumbing for Unit 340 Fx of Town Park <small>65%</small> </h4>
                    <div class="progress">
                        <div class="progress-bar bg-orange" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 65%"></div>
                    </div>
                </a></li>
            </ul>
        </li>
        <li class="footer"><a href="javascript:void(0);">View All Tasks</a> </li>
    </ul>
</li>

FxProperties/FxProperties/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>